apiVersion: v1
kind: ReplicationController
metadata:
  name: tweetstream-master
  # these labels can be applied automatically 
  # from the labels in the pod template if not set
  labels:
    app: tweetstream
    role: master
    tier: backend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 5
  # selector can be applied automatically 
  # from the labels in the pod template if not set
  # selector:
  #   app: guestbook
  #   role: master
  #   tier: backend
  template:
    metadata:
      labels:
        app: tweetstream
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: sharonhadar/tweetstream:ver1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
