apiVersion: v1
kind: Service
metadata:
  name: tweetstream_exam-master
  labels:
    app: tweetstream_exam
    role: master
    tier: backend
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
    targetPort: 6379
  selector:
    app: tweetstream_exam
    role: master
    tier: backend
